In [4]:
import pandas as pd 
import numpy as np

In [5]:
df= pd.read_csv('forestfires.csv')

In [6]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

BUSINESS TASK
Gold Coast Conservation Group is a 501(c)(4)concerned with the effects of climate change on campground, parks and lakes in locations with Mediterranean climate. Gold Coast Conservation Group endorses, lobbies and provides policy strategies to politicians. Gold Coast Conservation Group wants to study the causes of fires in public lands, the time of year when forest fires occur in high frequency and recommendations to prevent/minimize forest fires.

BUSINESS QUESTIONS
*What role does weather/climate play in causing fires in public lands?

*What time of year do most fires take place and what is the significance of the time frame?

*What are the soil conditions that cause fires in public lands?

*Provide recommendations to prevent fires in public lands and lakes.

*Can we extrapolate the study and apply the lessons to regions with similar climate conditions to the study?

*Can the findings be used as indicators of long term climate change effects in Santa Barbara county?

In [7]:
df.columns

Index(['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='object')

In [8]:
df.dtypes

X          int64
Y          int64
month     object
day       object
FFMC     float64
DMC      float64
DC       float64
ISI      float64
temp     float64
RH         int64
wind     float64
rain     float64
area     float64
dtype: object

The author noted that months and days are significant since a week day or weekend could affect the presence of hands to combat wildfires. since in many cases we donÂ´t know of specific days, we will asssign the month into seasons, and split the days of the week into weekday and weekend before transformation

In [9]:
#we will convert day to weekday and weekend
df['day'].unique()

array(['fri', 'tue', 'sat', 'sun', 'mon', 'wed', 'thu'], dtype=object)

In [10]:
df['month'].unique()

array(['mar', 'oct', 'aug', 'sep', 'apr', 'jun', 'jul', 'feb', 'jan',
       'dec', 'may', 'nov'], dtype=object)

In [11]:
#we will write a code to fix the months

df2= df.copy()

In [12]:
def get_season(month):
    # Define a mapping of months to seasons
    season_mapping = {
        "jan": "winter",
        "feb": "winter",
        "mar": "spring",
        "apr": "spring",
        "may": "spring",
        "jun": "summer",
        "jul": "summer",
        "aug": "summer",
        "sep": "autumn",
        "oct": "autumn",
        "nov": "autumn",
        "dec": "winter",
    }

    # Convert the input to lowercase to handle case variations
    month_lower = month.lower()

    # Check if the month is in the mapping, if not, return None
    return season_mapping.get(month_lower, None)


# Apply the get_season function to create a new column 'season'
df["season"] = df["month"].apply(get_season)

# Display the DataFrame with the new 'season' column
print(df)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  \
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

     season
0    spring
1    autumn
2    autumn
3    spring
4    spring
..      ...
512  summer
513  summer
514  summer
515  summer
516  autumn

[517 rows x 14 columns]

In [14]:
df

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,season
0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,spring
1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,autumn
2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,autumn
3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,spring
4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,4,3,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,summer
513,2,4,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,summer
514,7,4,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,summer
515,1,4,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,summer
516,6,3,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,autumn

In [15]:
df['day'].unique()

array(['fri', 'tue', 'sat', 'sun', 'mon', 'wed', 'thu'], dtype=object)

for days of the week we will factor in weekend and weekdays, as it is more likely that an unattended forest area will be more likely to burn longer than an actively watched forest, of course we will have a problem as we wonÂ´t consider office hours . Friday 9pm is almost same as saturday 12pm

In [16]:
def categorize_day(day):
    if day in ["sat", "sun"]:
        return "weekend"
    else:
        return "weekday"


# Apply the categorize_day function to create a new column 'day_category'
df["day_category"] = df["day"].apply(categorize_day)

In [17]:
df

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,season,day_category
0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,spring,weekday
1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,autumn,weekday
2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,autumn,weekend
3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,spring,weekday
4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,spring,weekend
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,4,3,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,summer,weekend
513,2,4,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,summer,weekend
514,7,4,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,summer,weekend
515,1,4,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,summer,weekend
516,6,3,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,autumn,weekday

In [19]:
#save new dataframe


df.to_csv('forestfireexp.csv', index=False)